{
  "root": true,
  "extends": [
      "eslint:recommended",
      "plugin:prettier/recommended",
      # "plugin:@typescript-eslint/recommended"
    ],
  "env": { "node": true },
  # "parser": "@typescript-eslint/parser",
  # "parserOptions": { "project": ["./tsconfig.json"] },
  "plugins": ["prettier"],
  "rules": { "prettier/prettier": "error" },
  # "ignorePatterns": ["src/**/*.test.ts", "src/frontend/generated/*"]
}
